//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.07 at 10:19:22 AM MESZ 
//


package ait.ffma.service.preservation.riskmanagement.api.lod.lodmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ait.ffma.service.preservation.riskmanagement.api.lod.lodmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ait.ffma.service.preservation.riskmanagement.api.lod.lodmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LODProperties }
     * 
     */
    public LODProperties createLODProperties() {
        return new LODProperties();
    }

    /**
     * Create an instance of {@link LODProperty.Value }
     * 
     */
    public LODProperty.Value createLODPropertyValue() {
        return new LODProperty.Value();
    }

    /**
     * Create an instance of {@link LODSource }
     * 
     */
    public LODSource createLODSource() {
        return new LODSource();
    }

    /**
     * Create an instance of {@link LODProperty.LODSources }
     * 
     */
    public LODProperty.LODSources createLODPropertyLODSources() {
        return new LODProperty.LODSources();
    }

    /**
     * Create an instance of {@link LODProperty }
     * 
     */
    public LODProperty createLODProperty() {
        return new LODProperty();
    }

    /**
     * Create an instance of {@link LODSource.OriginalValue }
     * 
     */
    public LODSource.OriginalValue createLODSourceOriginalValue() {
        return new LODSource.OriginalValue();
    }

}
