//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.07 at 10:19:22 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/LODProperties", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ait.ffma.service.preservation.riskmanagement.api.lod.lodmodel;
