//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 10:27:03 AM MEZ 
//


package ait.ffma.service.preservation.riskmanagement.api.riskanalysis.risk.riskmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ait.ffma.service.preservation.riskmanagement.api.riskanalysis.risk.riskmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ait.ffma.service.preservation.riskmanagement.api.riskanalysis.risk.riskmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RiskPropertySet.PropertySets }
     * 
     */
    public RiskPropertySet.PropertySets createRiskPropertySetPropertySets() {
        return new RiskPropertySet.PropertySets();
    }

    /**
     * Create an instance of {@link RiskPropertySet.PropertySetIDs }
     * 
     */
    public RiskPropertySet.PropertySetIDs createRiskPropertySetPropertySetIDs() {
        return new RiskPropertySet.PropertySetIDs();
    }

    /**
     * Create an instance of {@link RiskProperty }
     * 
     */
    public RiskProperty createRiskProperty() {
        return new RiskProperty();
    }

    /**
     * Create an instance of {@link RiskPropertySet.Properties }
     * 
     */
    public RiskPropertySet.Properties createRiskPropertySetProperties() {
        return new RiskPropertySet.Properties();
    }

    /**
     * Create an instance of {@link RiskClassification }
     * 
     */
    public RiskClassification createRiskClassification() {
        return new RiskClassification();
    }

    /**
     * Create an instance of {@link RiskPropertySet.PropertyIDs }
     * 
     */
    public RiskPropertySet.PropertyIDs createRiskPropertySetPropertyIDs() {
        return new RiskPropertySet.PropertyIDs();
    }

    /**
     * Create an instance of {@link RiskAnalysis }
     * 
     */
    public RiskAnalysis createRiskAnalysis() {
        return new RiskAnalysis();
    }

    /**
     * Create an instance of {@link RiskClassification.RiskFactors.RiskFactor }
     * 
     */
    public RiskClassification.RiskFactors.RiskFactor createRiskClassificationRiskFactorsRiskFactor() {
        return new RiskClassification.RiskFactors.RiskFactor();
    }

    /**
     * Create an instance of {@link RiskPropertySet }
     * 
     */
    public RiskPropertySet createRiskPropertySet() {
        return new RiskPropertySet();
    }

    /**
     * Create an instance of {@link RiskClassification.RiskFactors }
     * 
     */
    public RiskClassification.RiskFactors createRiskClassificationRiskFactors() {
        return new RiskClassification.RiskFactors();
    }

}
