//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 10:27:03 AM MEZ 
//


package ait.ffma.service.preservation.riskmanagement.api.riskanalysis.risk.riskmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RiskFactors" type="{http://www.example.org/RiskAnalysis}RiskPropertySet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "riskFactors"
})
@XmlRootElement(name = "RiskAnalysis")
public class RiskAnalysis {

    @XmlElement(name = "RiskFactors", required = true)
    private RiskPropertySet riskFactors;

    /**
     * Gets the value of the riskFactors property.
     * 
     * @return
     *     possible object is
     *     {@link RiskPropertySet }
     *     
     */
    public RiskPropertySet getRiskFactors() {
        return riskFactors;
    }

    /**
     * Sets the value of the riskFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskPropertySet }
     *     
     */
    public void setRiskFactors(RiskPropertySet value) {
        this.riskFactors = value;
    }

}
