package ait.ffma.domain.preservation;

import ait.ffma.domain.BaseFfmaDomainObject;
import ait.ffma.domain.FieldDefEnum;
import ait.ffma.factory.ComponentNameConstants;


//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2010.11.11 at 09:31:52 AM MEZ 
//


/**
* <p>Java class for linkingAgentIdentifierComplexType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="linkingAgentIdentifierComplexType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element ref="{info:lc/xmlns/premis-v2}linkingAgentIdentifierType"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}linkingAgentIdentifierValue"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}linkingAgentRole" maxOccurs="unbounded" minOccurs="0"/>
*       &lt;/sequence>
*       &lt;attGroup ref="{http://www.w3.org/1999/xlink}simpleLink"/>
*       &lt;attribute name="LinkAgentXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
public class LinkingAgentIdentifierComplexType extends BaseFfmaDomainObject {

	private static final long serialVersionUID = 7187571730857195525L;
	
	public enum FieldsEnum implements FieldDefEnum {
		LinkingAgentIdentifierType   { public Class<?> evalType() { return String.class; } },
		LinkingAgentIdentifierValue  { public Class<?> evalType() { return String.class; } },
		Type                         { public Class<?> evalType() { return String.class; } },
		AgentId                      { public Class<?> evalType() { return String.class; } };

		public String evalName() { return this.name(); }
	}
	
	public FieldDefEnum[] getFieldsEnum() {
		return FieldsEnum.values();
	}

	public LinkingAgentIdentifierComplexType () {
		setFfmaObjectName(LinkingAgentIdentifierComplexType.class.getSimpleName());
		setComponentName(ComponentNameConstants.COMPONENT_PRESERVATION_RISKMANAGEMENT);
	}	

	 /**
	  * Gets the value of the linkingAgentIdentifierType property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getLinkingAgentIdentifierType() {
		 return getString(FieldsEnum.LinkingAgentIdentifierType.name());
	 }
	
	 /**
	  * Sets the value of the linkingAgentIdentifierType property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setLinkingAgentIdentifierType(String value) {
	     put(FieldsEnum.LinkingAgentIdentifierType.name(), value);	
	 }
	
	 /**
	  * Gets the value of the linkingAgentIdentifierValue property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getLinkingAgentIdentifierValue() {
	     return getString(FieldsEnum.LinkingAgentIdentifierValue.name());
	 }
	
	 /**
	  * Sets the value of the linkingAgentIdentifierValue property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setLinkingAgentIdentifierValue(String value) {
	     put(FieldsEnum.LinkingAgentIdentifierValue.name(), value);	
	 }
	
	 /**
	  * Gets the value of the type property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getType() {
		 return getString(FieldsEnum.Type.name());
	 }
	
	 /**
	  * Sets the value of the type property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setType(String value) {
	     put(FieldsEnum.Type.name(), value);	
	 }
	
	 /**
	  * Gets the value of the actuate property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getAgentId() {
	     return getString(FieldsEnum.AgentId.name());
	 }
	
	 /**
	  * Sets the value of the actuate property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setAgentId(String value) {
	     put(FieldsEnum.AgentId.name(), value);	
	 }

}
