package ait.ffma.domain.preservation;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2010.11.11 at 09:31:52 AM MEZ 
//

import ait.ffma.domain.BaseFfmaDomainObject;
import ait.ffma.domain.FieldDefEnum;
import ait.ffma.factory.ComponentNameConstants;


/**
* <p>Java class for eventComplexType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="eventComplexType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element ref="{info:lc/xmlns/premis-v2}eventIdentifier"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}eventType"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}eventDateTime"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}eventDetail" minOccurs="0"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}eventOutcomeInformation" maxOccurs="unbounded" minOccurs="0"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}linkingAgentIdentifier" maxOccurs="unbounded" minOccurs="0"/>
*         &lt;element ref="{info:lc/xmlns/premis-v2}linkingObjectIdentifier" maxOccurs="unbounded" minOccurs="0"/>
*       &lt;/sequence>
*       &lt;attribute name="xmlID" type="{http://www.w3.org/2001/XMLSchema}ID" />
*       &lt;attribute name="version" type="{info:lc/xmlns/premis-v2}versionSimpleType" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
public class EventComplexType extends BaseFfmaDomainObject {

	private static final long serialVersionUID = 7571040504564518950L;

	public enum FieldsEnum implements FieldDefEnum {
		EventIdentifier            { public Class<?> evalType() { return EventIdentifierComplexType.class; } },
		EventDetail                { public Class<?> evalType() { return String.class; } },
		EventType                  { public Class<?> evalType() { return String.class; } },
		Version                    { public Class<?> evalType() { return String.class; } },
		EventOutcomeInformation    { public Class<?> evalType() { return EventOutcomeInformationComplexType.class; } };

		public String evalName() { return this.name(); }
	}

	public FieldDefEnum[] getFieldsEnum() {
		return FieldsEnum.values();
	}
	
	public EventComplexType () {
		setFfmaObjectName(EventComplexType.class.getSimpleName());
		setComponentName(ComponentNameConstants.COMPONENT_PRESERVATION_RISKMANAGEMENT);
	}
	
	 /**
	  * Gets the value of the eventIdentifier property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link EventIdentifierComplexType }
	  *     
	  */
	 public EventIdentifierComplexType getEventIdentifier() {	 
		 return(EventIdentifierComplexType) get(FieldsEnum.EventIdentifier.name());
	 }
	
	 /**
	  * Sets the value of the eventIdentifier property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link EventIdentifierComplexType }
	  *     
	  */
	 public void setEventIdentifier(EventIdentifierComplexType value) {
		 put(FieldsEnum.EventIdentifier.name(), value);	
	 }
	
 	 /**
	  * @return the eventOutcomeInformationComplexType
	  */
	 public EventOutcomeInformationComplexType getEventOutcomeInformationComplexType() {
 		return (EventOutcomeInformationComplexType) get(FieldsEnum.EventOutcomeInformation.name()); 
	 }

	 /**
	  * @param eventOutcomeInformationComplexType the eventOutcomeInformationComplexType to set
	  */
	 public void setEventOutcomeInformationComplexType(
	 		EventOutcomeInformationComplexType value) {
		 put(FieldsEnum.EventOutcomeInformation.name(), value);
	 }

	 /**
	  * Gets the value of the eventType property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getEventType() {
		 return getString(FieldsEnum.EventType.name());	
	 }
	
	 /**
	  * Sets the value of the eventType property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setEventType(String value) {
		 put(FieldsEnum.EventType.name(), value);	
	 }
	
	 /**
	  * Gets the value of the eventDetail property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getEventDetail() {
		 return getString(FieldsEnum.EventDetail.name());	
	 }
	
	 /**
	  * Sets the value of the eventDetail property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setEventDetail(String value) {
		 put(FieldsEnum.EventDetail.name(), value);	
	 }
	
	 /**
	  * Gets the value of the version property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getVersion() {
		 return getString(FieldsEnum.Version.name());	
	 }
	
	 /**
	  * Sets the value of the version property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setVersion(String value) {
		 put(FieldsEnum.Version.name(), value);	
	 }

}
