//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 10:27:03 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/RiskAnalysis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ait.ffma.service.preservation.riskmanagement.api.riskanalysis.risk.riskmodel;
